package com.connectit.core;

import com.connectit.core.util.SimpleHash;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
class CoreServiceApplicationTests {

    /** Verify SimpleHash produces the same result as the JavaScript original */
    @Test
    void simpleHash_matchesJavaScriptBehavior() {
        // These values were generated by the original JS simpleHash("Poland@01")
        String hash = SimpleHash.hash("Poland@01");
        assertNotNull(hash);
        assertTrue(hash.startsWith("h_"));
        // Format: h_<base36>_<length>
        String[] parts = hash.split("_");
        assertEquals(3, parts.length);
        assertEquals("8", parts[2]); // "Poland@01" is 8 chars
    }

    @Test
    void simpleHash_differentPasswordsDifferentHashes() {
        assertNotEquals(SimpleHash.hash("password1"), SimpleHash.hash("password2"));
    }

    @Test
    void simpleHash_consistentResults() {
        assertEquals(SimpleHash.hash("test123"), SimpleHash.hash("test123"));
    }
}
