package com.connectit.core;

import com.connectit.core.util.SimpleHash;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
class CoreServiceApplicationTests {

    @org.springframework.beans.factory.annotation.Autowired
    private org.springframework.jdbc.core.JdbcTemplate jdbcTemplate;

    @Test
    void databaseSeeder_seedsDefaultDataSuccessfully() {
        // Verify default settings categories are seeded
        Integer categoryCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM settings_categories WHERE id IN ('cat_default_1', 'cat_default_2')", Integer.class
        );
        assertEquals(2, categoryCount, "Settings categories should be seeded");

        // Verify default settings subcategories are seeded and linked
        java.util.List<java.util.Map<String, Object>> subcategories = jdbcTemplate.queryForList(
            "SELECT category_id FROM settings_subcategories WHERE id IN ('sub_default_1', 'sub_default_2', 'sub_default_3')"
        );
        assertEquals(3, subcategories.size(), "Three subcategories should be seeded");
        for (java.util.Map<String, Object> sub : subcategories) {
            assertNotNull(sub.get("category_id"), "Subcategory parent category_id must not be null");
        }

        // Verify default incident categories are seeded
        Integer incidentCategoryCount = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM incident_categories", Integer.class
        );
        assertTrue(incidentCategoryCount >= 10, "At least 10 incident categories should be seeded");
    }

    @Test
    void subcategoryCreation_linksParentCategoryIdCorrectly() {
        String testSubId = "sub_test_" + System.currentTimeMillis();
        String testCatId = "cat_default_1"; // IT Support

        // Insert subcategory simulating Settings page creation payload
        jdbcTemplate.update(
            "INSERT INTO settings_subcategories (id, name, description, category_id, status, company_id) VALUES (?, ?, ?, ?, ?, ?)",
            testSubId, "z", "z description", testCatId, "active", "1"
        );

        // Fetch back and assert linkage
        java.util.Map<String, Object> subcategory = jdbcTemplate.queryForMap(
            "SELECT category_id FROM settings_subcategories WHERE id = ?", testSubId
        );
        assertEquals(testCatId, subcategory.get("category_id"), "Created subcategory must have the correct category_id linked");

        // Clean up
        jdbcTemplate.update("DELETE FROM settings_subcategories WHERE id = ?", testSubId);
    }

    @Test
    void simpleHash_matchesJavaScriptBehavior() {
        // These values were generated by the original JS simpleHash("Poland@01")
        String hash = SimpleHash.hash("Poland@01");
        assertNotNull(hash);
        assertTrue(hash.startsWith("h_"));
        // Format: h_<base36>_<length>
        String[] parts = hash.split("_");
        assertEquals(3, parts.length);
        assertEquals("9", parts[2]); // "Poland@01" is 9 chars
    }

    @Test
    void simpleHash_differentPasswordsDifferentHashes() {
        assertNotEquals(SimpleHash.hash("password1"), SimpleHash.hash("password2"));
    }

    @Test
    void simpleHash_consistentResults() {
        assertEquals(SimpleHash.hash("test123"), SimpleHash.hash("test123"));
    }

    @Test
    void dashboardLayout_crudOperations() {
        String testUser = "user_test_uid";
        String layoutJson = "[\"Open Tickets\", \"Closed Tickets\"]";
        String id = "lay_test";

        // Insert
        jdbcTemplate.update(
            "INSERT INTO settings_dashboard_layouts (id, user_uid, layout_json) VALUES (?, ?, ?)",
            id, testUser, layoutJson
        );

        // Fetch
        String fetched = jdbcTemplate.queryForObject(
            "SELECT layout_json FROM settings_dashboard_layouts WHERE user_uid = ?",
            String.class, testUser
        );
        assertEquals(layoutJson, fetched);

        // Update
        String updatedLayout = "[\"Open Tickets\"]";
        jdbcTemplate.update(
            "UPDATE settings_dashboard_layouts SET layout_json = ? WHERE user_uid = ?",
            updatedLayout, testUser
        );
        String fetchedUpdated = jdbcTemplate.queryForObject(
            "SELECT layout_json FROM settings_dashboard_layouts WHERE user_uid = ?",
            String.class, testUser
        );
        assertEquals(updatedLayout, fetchedUpdated);

        // Delete
        jdbcTemplate.update("DELETE FROM settings_dashboard_layouts WHERE user_uid = ?", testUser);
        Integer count = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM settings_dashboard_layouts WHERE user_uid = ?",
            Integer.class, testUser
        );
        assertEquals(0, count);
    }

    @Test
    void planningModule_crudOperations() {
        String testId = "tgt_test_123";
        // Insert Target
        jdbcTemplate.update(
            "INSERT INTO planning_targets (id, target_type, target_period, metric_name, target_value, actual_value, assignee_uid) VALUES (?, ?, ?, ?, ?, ?, ?)",
            testId, "Global", "2026-Q3", "SLA Resolution Rate", 95.0, 92.5, "assignee_123"
        );

        // Fetch
        Double targetVal = jdbcTemplate.queryForObject(
            "SELECT target_value FROM planning_targets WHERE id = ?",
            Double.class, testId
        );
        assertEquals(95.0, targetVal);

        // Delete
        jdbcTemplate.update("DELETE FROM planning_targets WHERE id = ?", testId);
        Integer count = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM planning_targets WHERE id = ?",
            Integer.class, testId
        );
        assertEquals(0, count);
    }

    @Test
    void calendarEvents_crudOperations() {
        String testId = "evt_test_123";
        // Insert Event
        jdbcTemplate.update(
            "INSERT INTO planning_calendar_events (id, title, event_type, event_date, details) VALUES (?, ?, ?, ?, ?)",
            testId, "Test Release", "Release", java.sql.Date.valueOf("2026-06-16"), "Test Details"
        );

        // Fetch
        String title = jdbcTemplate.queryForObject(
            "SELECT title FROM planning_calendar_events WHERE id = ?",
            String.class, testId
        );
        assertEquals("Test Release", title);

        // Delete
        jdbcTemplate.update("DELETE FROM planning_calendar_events WHERE id = ?", testId);
        Integer count = jdbcTemplate.queryForObject(
            "SELECT COUNT(*) FROM planning_calendar_events WHERE id = ?",
            Integer.class, testId
        );
        assertEquals(0, count);
    }
}
